[mysql]
# address = "50.18.79.42"
address = "localhost"
port = "3307"
db_name = "pledge_v21"
user_name = "pledge_v21"
password = "pledge_v21"
max_open_conns = 0
max_idle_conns = 0
max_life_time = 0

[redis]
# address = "50.18.79.42"
address = "localhost"
port = "6380"
db = 1
user_name = ""
password = "pledger_web3"
max_idle = 0
max_active = 0
idle_timeout = 0

#[testnet]
#chain_id = "11155111"
#net_url = "https://ethereum-sepolia-rpc.publicnode.com"
#plgr_address = "0x351d7443282751Bc31360fd2a5f868605d6e1a15"
#pledge_pool_token = "0x23FB053aa94901F3922475304639Bc20672d9b08"
#bsc_pledge_oracle_token = "0x18bC845077415Ed55600684f1E5B475247cF5161"

[testnet]
chain_id = "97"
net_url = "https://data-seed-prebsc-1-s1.binance.org:8545"
plgr_address = "0X6AA91CBFE045F9D154050226FCC830DDBA886CED"
pledge_pool_token = "0x216f718A983FCCb462b338FA9c60f2A89199490c"
bsc_pledge_oracle_token = "0xd96DBDC193617A0cD4bbf38E78a0fB4799A8E554"


[mainnet]
chain_id = "56"
net_url = "https://bsc-dataseed.binance.org"
plgr_address = "0x6aa91cbfe045f9d154050226fcc830ddba886ced"
pledge_pool_token = "0x25C3f3d3E3299d7C56700CE54303Fbe1E6a16fee"
bsc_pledge_oracle_token = "0x4Aa9EB3149089D7208C9C0403BF1b9bA25ff05BD"

[token]
logo_url = "https://tokens.pancakeswap.finance/pancakeswap-top-100.json"

[defaultadmin]
username = "admin"
password = "password"

[jwt]
expire_time = 2592000
secret_key = "243223ffslsfsldfl412fdsfsdf"

[env]
port = "8080"
version = "21"
protocol = "https"
task_duration = 2
task_extend_duration = 5
wss_timeout_duration = 20
domain_name = "118.195.185.245:8080"

[threshold]
pledge_pool_token_threshold_bnb = "100000000000000000"

[email]
username = "XXXX@gmail.com"
pwd = "XXXX"
host = "smtp.gmail.com"
port = "587"
from = "pledge beidge <test@gmail.com>"
subject = "Insufficient balance of bridge account"
to = ["XXXX@outlook.com"]
cc = ["XXXX@126.com"]
